common: &common
  env: staging
  tz: America/Santiago
  execution_date: 2024-08-08
  database: staging
time_serie: &time_serie
  group_columns: [city, product_id]
  time_column: date
  target_column: sales
create_database:
  <<:
    - *common
ingestion:
  <<:
    - *common
  dir: "data"
  sep: ","
  cities: ["M5"]
split:
  <<:
    - *common
    - *time_serie
  time_delta: 68
  test_size: 7
  freq: 1D
model: &model
  <<:
    - *common
    - *time_serie
  test_size: 7
  steps: 9
  freq: 1D
models:
  ExponentialSmoothing:
    <<: *model
    model_cls: ExponentialSmoothing
    model_params:
      random_state: 0
      seasonal_periods: 7
  Prophet:
    <<: *model
    model_cls: Prophet
  XGBModel:
    <<: *model
    model_cls: XGBModel
    model_params:
      random_state: 0
      objective: reg:squarederror
      lags: 7
      nthread: 1
      max_depth: 6
      learning_rate: 0.3
      gamma: 0
      lambda: 1
      alpha: 0
  RandomForest:
    <<: *model
    model_cls: RandomForest
    model_params:
      random_state: 0
      lags: 7
      n_jobs: 1
      n_estimators: 100
      max_depth: 6
  Croston:
    <<: *model
    model_cls: Croston
    model_params:
      version: sba
  NaiveMean:
    <<: *model
    model_cls: NaiveMean
  NaiveMovingAverage:
    <<: *model
    model_cls: NaiveMovingAverage
    model_params:
      input_chunk_length: 7
evaluation:
  <<:
    - *common
    - *time_serie
  metrics: [rmse, mae]
  model_selection_metric: mae
  freq: 1D
output:
  <<:
    - *common
    - *time_serie
  window_size: 7
